/*++

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Copyright (c) 2019-2020 Bohdan Yevtukh. All rights reserved.

Module Name:

    OsrUsbFx2PnP.c

Abstract:

    This module contains routines to handle Plug and Play (PnP) requests for
    the OSR USB FX-2 device.

Environment:

    Kernel mode only.

--*/

#include "pch.h"
#include "OsrUsbFx2Logging.h"
#include "OsrUsbFx2Private.h"

#if defined (EVENT_TRACING)
//
// The trace message header (.tmh) file must be included in a source file
// before any WPP macro calls and after defining a WPP_CONTROL_GUIDS
// macro (defined in OsrUsbFx2Logging.h). During the compilation, WPP scans
// the source files for OSR_LOG...() calls and builds a .tmh file which stores
// a unique data GUID for each message, the text resource string for each
// message, and the data types of the variables passed in for each message.
// This file is automatically generated and used during post-processing.
//
#include "OsrUsbFx2PnP.tmh"
#endif /* defined (EVENT_TRACING) */

DRIVER_DISPATCH OsrUsbFx2_StartDevice;
DRIVER_DISPATCH OsrUsbFx2_QueryRemoveDevice;
DRIVER_DISPATCH OsrUsbFx2_RemoveDevice;
DRIVER_DISPATCH OsrUsbFx2_CancelRemoveDevice;
DRIVER_DISPATCH OsrUsbFx2_StopDevice;
DRIVER_DISPATCH OsrUsbFx2_QueryStopDevice;
DRIVER_DISPATCH OsrUsbFx2_CancelStopDevice;
DRIVER_DISPATCH OsrUsbFx2_QueryCapabilities;
DRIVER_DISPATCH OsrUsbFx2_SurpriseRemoval;

//
// Define the sections that allow for discarding (i.e. paging) some of the code
//

#if defined (ALLOC_PRAGMA)
#pragma alloc_text(PAGE, OsrUsbFx2_DispatchPnP)
#pragma alloc_text(PAGE, OsrUsbFx2_StartDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_QueryRemoveDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_RemoveDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_CancelRemoveDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_StopDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_QueryStopDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_CancelStopDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_QueryCapabilities)
#pragma alloc_text(PAGE, OsrUsbFx2_SurpriseRemoval)
#endif /* defined (ALLOC_PRAGMA) */

__useHeader
NTSTATUS
OsrUsbFx2_DispatchPnP (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This routine handles the Plug and Play (PnP) I/O operations, some of which
    are ignored and passed on the IRP to the lower driver.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;
    NTSTATUS status = STATUS_SUCCESS;

    PAGED_CODE ();

    OSR_LOG_TRACE ("Entering %!FUNC!(0x%p, ...).", DeviceObject);

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MJ_PNP == irpStack->MajorFunction);

    OSR_LOG_TRACE ("Leaving %!FUNC!: %!STATUS!.", status);

    return status;
}

__useHeader
NTSTATUS
OsrUsbFx2_StartDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the start device Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_START_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_QueryRemoveDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the query remove device
    Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_QUERY_REMOVE_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_RemoveDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the remove device Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_REMOVE_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_CancelRemoveDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the cancel remove device
    Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_CANCEL_REMOVE_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_StopDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the stop device Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_STOP_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_QueryStopDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the query stop device
    Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_QUERY_STOP_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_CancelStopDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the cancel stop device
    Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_CANCEL_STOP_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_QueryCapabilities (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the query capabilities
    Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_QUERY_CAPABILITIES == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_SurpriseRemoval (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the surprise removal
    Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_SURPRISE_REMOVAL == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}
