/*++

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Copyright (c) 2019-2020 Bohdan Yevtukh. All rights reserved.

Module Name:

    OsrUsbFx2PnP.c

Abstract:

    This module contains routines to handle Plug and Play (PnP) requests for
    the OSR USB FX-2 device.

Environment:

    Kernel mode only.

--*/

#include "pch.h"
#include "OsrUsbFx2Logging.h"
#include "OsrUsbFx2Private.h"

#if defined (EVENT_TRACING)
//
// The trace message header (.tmh) file must be included in a source file
// before any WPP macro calls and after defining a WPP_CONTROL_GUIDS
// macro (defined in OsrUsbFx2Logging.h). During the compilation, WPP scans
// the source files for OSR_LOG...() calls and builds a .tmh file which stores
// a unique data GUID for each message, the text resource string for each
// message, and the data types of the variables passed in for each message.
// This file is automatically generated and used during post-processing.
//
#include "OsrUsbFx2PnP.tmh"
#endif /* defined (EVENT_TRACING) */

DRIVER_DISPATCH OsrUsbFx2_StartDevice;
DRIVER_DISPATCH OsrUsbFx2_QueryRemoveDevice;
DRIVER_DISPATCH OsrUsbFx2_RemoveDevice;
DRIVER_DISPATCH OsrUsbFx2_CancelRemoveDevice;
DRIVER_DISPATCH OsrUsbFx2_StopDevice;
DRIVER_DISPATCH OsrUsbFx2_QueryStopDevice;
DRIVER_DISPATCH OsrUsbFx2_CancelStopDevice;
DRIVER_DISPATCH OsrUsbFx2_QueryCapabilities;
DRIVER_DISPATCH OsrUsbFx2_SurpriseRemoval;

//
// Define the sections that allow for discarding (i.e. paging) some of the data
//

#if defined (ALLOC_DATA_PRAGMA)
#pragma const_seg(push, "PAGECONST")
#endif /* defined (ALLOC_DATA_PRAGMA) */

//
// A dispatch table consisting of an array of entry points for the driver's
// Plug and Play (PnP) dispatch routines, the array's index values are the
// IRP_MN_XXX values representing each IRP minor function code
//
CONST PDRIVER_DISPATCH OsrUsbFx2_PnPDispatchTable[] = {
    &OsrUsbFx2_StartDevice,                  // IRP_MN_START_DEVICE
    &OsrUsbFx2_QueryRemoveDevice,            // IRP_MN_QUERY_REMOVE_DEVICE
    &OsrUsbFx2_RemoveDevice,                 // IRP_MN_REMOVE_DEVICE
    &OsrUsbFx2_CancelRemoveDevice,           // IRP_MN_CANCEL_REMOVE_DEVICE
    &OsrUsbFx2_StopDevice,                   // IRP_MN_STOP_DEVICE
    &OsrUsbFx2_QueryStopDevice,              // IRP_MN_QUERY_STOP_DEVICE
    &OsrUsbFx2_CancelStopDevice,             // IRP_MN_CANCEL_STOP_DEVICE

    NULL,                                    // IRP_MN_QUERY_DEVICE_RELATIONS
    NULL,                                    // IRP_MN_QUERY_INTERFACE
    &OsrUsbFx2_QueryCapabilities,            // IRP_MN_QUERY_CAPABILITIES
    NULL,                                    // IRP_MN_QUERY_RESOURCES
    NULL,                                    // IRP_MN_QUERY_RESOURCE_REQUIREMENTS
    NULL,                                    // IRP_MN_QUERY_DEVICE_TEXT
    NULL,                                    // IRP_MN_FILTER_RESOURCE_REQUIREMENTS

    NULL,                                    // ???
    NULL,                                    // IRP_MN_READ_CONFIG
    NULL,                                    // IRP_MN_WRITE_CONFIG
    NULL,                                    // IRP_MN_EJECT
    NULL,                                    // IRP_MN_SET_LOCK
    NULL,                                    // IRP_MN_QUERY_ID
    NULL,                                    // IRP_MN_QUERY_PNP_DEVICE_STATE
    NULL,                                    // IRP_MN_QUERY_BUS_INFORMATION
    NULL,                                    // IRP_MN_DEVICE_USAGE_NOTIFICATION
    NULL,                                    // IRP_MN_SURPRISE_REMOVAL

    NULL                                     // IRP_MN_QUERY_LEGACY_BUS_INFORMATION

#if (NTDDI_VERSION >= NTDDI_WIN7)
    , NULL                                   // IRP_MN_DEVICE_ENUMERATED
#endif /* NTDDI_VERSION >= NTDDI_WIN7 */
};

#if defined (ALLOC_DATA_PRAGMA)
#pragma const_seg(pop)
#endif /* defined (ALLOC_DATA_PRAGMA) */

//
// Define the sections that allow for discarding (i.e. paging) some of the code
//

#if defined (ALLOC_PRAGMA)
#pragma alloc_text(PAGE, OsrUsbFx2_DispatchPnP)
#pragma alloc_text(PAGE, OsrUsbFx2_StartDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_QueryRemoveDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_RemoveDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_CancelRemoveDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_StopDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_QueryStopDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_CancelStopDevice)
#pragma alloc_text(PAGE, OsrUsbFx2_QueryCapabilities)
#pragma alloc_text(PAGE, OsrUsbFx2_SurpriseRemoval)
#endif /* defined (ALLOC_PRAGMA) */

__useHeader
NTSTATUS
OsrUsbFx2_DispatchPnP (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This routine handles the Plug and Play (PnP) I/O operations, some of which
    are ignored and passed on the IRP to the lower driver.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PDRIVER_DISPATCH driverDispatch;
    POSRUSBFX2_DEVICE_EXTENSION deviceExtension;
    PIO_STACK_LOCATION irpStack;
    NTSTATUS status;

    PAGED_CODE ();

    OSR_LOG_TRACE ("Entering %!FUNC!(0x%p, ...).", DeviceObject);

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MJ_PNP == irpStack->MajorFunction);

    //
    // All drivers for a device must have the opportunity to handle PnP IRPs
    // for the device unless one of the drivers encounters an error, the PnP
    // manager sends IRPs to the top driver in a device stack, function drivers
    // pass the IRP down to the next driver, and the parent bus driver
    // completes the IRP
    //
    // If a driver receives an IRP with a code it does not handle, it
    // must not fail the IRP, instead it must pass such an IRP down to the next
    // driver without modifying the IRP's status
    //

    deviceExtension = DeviceObject->DeviceExtension;

    //
    // Try to grab the release lock, so the device object cannot be detached
    // while the IRP is being processed by the driver
    //
    // It is a responsibility of the particular dispatch routine to release
    // the remove lock once the operation is complete, if processing is
    // synchronous then it should be released inside the dispatch routine,
    // otherwise in the context of the completion routine
    //
    status = IoAcquireRemoveLock (&deviceExtension->RemoveLock, Irp);

    if (NT_SUCCESS (status)) {

        driverDispatch = NULL;

        if (irpStack->MinorFunction < ARRAYSIZE(OsrUsbFx2_PnPDispatchTable)) {
            driverDispatch = OsrUsbFx2_PnPDispatchTable[irpStack->MinorFunction];
        }

        //
        // Even if the IRP minor function code is within the valid range it
        // can be unhandled by this driver as described above, such handlers
        // are initialized with NULL pointer value
        //
        if (NULL != driverDispatch) {
            status = driverDispatch (DeviceObject, Irp);
        }
        else {

            //
            // Pass an IRP down a device stack
            //

            IoSkipCurrentIrpStackLocation (Irp);
            status = IoCallDriver (deviceExtension->TopDeviceObject, Irp);

            IoReleaseRemoveLock (&deviceExtension->RemoveLock, Irp);
        }
    }
    else {

        OSR_LOG_WARNING (
            "Failed to acquire the device remove lock: %!STATUS!.",
            status
            );

        //
        // The device object is about to be deleted, set the corresponding
        // status value, so the caller is able to react correctly and does not
        // reuse this object for any further operations
        //
        // N.B. Typically on this point status is set to the
        //      STATUS_DELETE_PENDING value that can be interpreted incorrectly
        //
        status = STATUS_NO_SUCH_DEVICE;

        Irp->IoStatus.Status = status;
        IoCompleteRequest (Irp, IO_NO_INCREMENT);
    }

    OSR_LOG_TRACE ("Leaving %!FUNC!: %!STATUS!.", status);

    return status;
}

__useHeader
NTSTATUS
OsrUsbFx2_StartDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the start device Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_START_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_QueryRemoveDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the query remove device
    Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_QUERY_REMOVE_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_RemoveDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the remove device Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_REMOVE_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_CancelRemoveDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the cancel remove device
    Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_CANCEL_REMOVE_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_StopDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the stop device Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_STOP_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_QueryStopDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the query stop device
    Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_QUERY_STOP_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_CancelStopDevice (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the cancel stop device
    Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_CANCEL_STOP_DEVICE == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_QueryCapabilities (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the query capabilities
    Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_QUERY_CAPABILITIES == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}

__useHeader
NTSTATUS
OsrUsbFx2_SurpriseRemoval (
    PDEVICE_OBJECT DeviceObject,
    PIRP Irp
    )
/*++

Routine Description:

    This dispatch routine services the surprise removal
    Plug and Play (PnP) IRP.

Arguments:

    DeviceObject - Caller-supplied pointer to a DEVICE_OBJECT structure.
    This is the device object for the target device, previously created
    by the OsrUsbFx2_PnPAddDevice routine.

    Irp - Caller-supplied pointer to an IRP structure that describes
    the requested I/O operation.

Return Value:

    Various NTSTATUS codes.

--*/
{
    PIO_STACK_LOCATION irpStack;

    DBG_UNREFERENCED_PARAMETER (DeviceObject);
    DBG_UNREFERENCED_PARAMETER (Irp);

    PAGED_CODE ();

    irpStack = IoGetCurrentIrpStackLocation (Irp);

    ASSERT (IRP_MN_SURPRISE_REMOVAL == irpStack->MinorFunction);

    return STATUS_SUCCESS;
}
