/*++

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Copyright (c) 2019 Bohdan Yevtukh. All rights reserved.

Module Name:

    OsrUsbFx2Driver.c

Abstract:

    This module contains the code to initialize the OSR USB FX2 device driver.

Environment:

    Kernel mode only.

--*/

#include "pch.h"
#include "OsrUsbFx2Logging.h"

#if defined (EVENT_TRACING)
//
// The trace message header (.tmh) file must be included in a source file
// before any WPP macro calls and after defining a WPP_CONTROL_GUIDS
// macro (defined in OsrUsbFx2Logging.h). During the compilation, WPP scans
// the source files for OSR_LOG...() calls and builds a .tmh file which stores
// a unique data GUID for each message, the text resource string for each
// message, and the data types of the variables passed in for each message.
// This file is automatically generated and used during post-processing.
//
#include "OsrUsbFx2Driver.tmh"
#endif /* defined (EVENT_TRACING) */

DRIVER_INITIALIZE DriverEntry;
DRIVER_UNLOAD OsrUsbFx2Unload;

//
// Define the sections that allow for discarding (i.e. paging) some of the code
//

#if defined (ALLOC_PRAGMA)
#pragma alloc_text(INIT, DriverEntry)
#pragma alloc_text(PAGE, OsrUsbFx2Unload)
#endif /* defined (ALLOC_PRAGMA) */

__useHeader
NTSTATUS
DriverEntry (
    PDRIVER_OBJECT DriverObject,
    PUNICODE_STRING RegistryPath
    )
/*++

Routine Description:

    DriverEntry initializes the driver and is the first routine called by the
    system after the driver is loaded.

Arguments:

    DriverObject - Represents the instance of the function driver that is loaded
    into memory. DriverEntry must initialize members of DriverObject before it
    returns to the caller. DriverObject is allocated by the system before the
    driver is loaded, and it is released by the system after the system unloads
    the function driver from memory.

    RegistryPath - Represents the driver specific path in the Registry.
    The function driver can use the path to store driver related data between
    reboots. The path does not store hardware instance specific data.

Return Value:

    STATUS_SUCCESS if successful,
    STATUS_UNSUCCESSFUL otherwise.

--*/
{
    OSR_LOG_INIT (DriverObject, RegistryPath);

    OSR_LOG_INFORMATION (
        "Initializing %s with parameters: DriverObject=0x%p, RegistryPath=%wZ.",
        OSR_USB_FX_2_LOGGING_NAME,
        DriverObject,
        RegistryPath
        );

    DriverObject->DriverUnload = &OsrUsbFx2Unload;

    return STATUS_SUCCESS;
}

__useHeader
VOID
OsrUsbFx2Unload (
    PDRIVER_OBJECT DriverObject
    )
/*++

Routine Description:

    OsrUsbFx2Unload routine performs any operations that are necessary before
    the system unloads the driver.

Arguments:

    DriverObject - Caller-supplied pointer to a DRIVER_OBJECT structure. This is
    the driver's driver object.

Return Value:

    None.

--*/
{
    PAGED_CODE ();

    OSR_LOG_INFORMATION (
        "Unloading driver %s: DriverObject=0x%p.",
        OSR_USB_FX_2_LOGGING_NAME,
        DriverObject
        );

    OSR_LOG_CLEANUP (DriverObject);
}
