/*++

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Copyright (c) 2019 Bohdan Yevtukh. All rights reserved.

Module Name:

    OsrUsbFx2Public.h

Abstract:

    This module contains the common declarations shared by driver and user
    applications.

--*/

#if !defined(OSRUSBFX2PUBLIC_H__2EA744D4_FDCE_4827_8FFE_8F180E4EB4F9__INCLUDED_)
#define OSRUSBFX2PUBLIC_H__2EA744D4_FDCE_4827_8FFE_8F180E4EB4F9__INCLUDED_

#if defined(_MSC_VER) && (_MSC_VER > 1000)
#pragma once
#endif /* defined(_MSC_VER) && (_MSC_VER > 1000) */

#include <initguid.h>

//
// Define an Interface GUID for the OSR USB FX-2 LK device
//
// This GUID can be used by user application to control the device
//

//
// {943F60D9-C131-447B-9DD7-51F28BACBA12}
//
DEFINE_GUID(GUID_DEVINTERFACE_OSRUSBFX2,
    0x943f60d9, 0xc131, 0x447b, 0x9d, 0xd7, 0x51, 0xf2, 0x8b, 0xac, 0xba, 0x12);

#endif /* !defined(OSRUSBFX2PUBLIC_H__2EA744D4_FDCE_4827_8FFE_8F180E4EB4F9__INCLUDED_) */
